import { globalStyles } from '@/styles/global';
import { Global } from '@emotion/react';
import type { AppProps } from 'next/app';
import Head from 'next/head';

interface ServiceAppProps {}

const MyApp = ({ Component, pageProps }: AppProps<ServiceAppProps>) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Global styles={globalStyles}></Global>
      <Component {...pageProps} />
    </>
  );
};

export default MyApp;
