import Head from 'next/head';
import type { AppProps } from 'next/app';

import { RecoilRoot } from 'recoil';
import { globalStyles } from '@/styles/global';
import { Global } from '@emotion/react';
import { AnimatePresence } from 'framer-motion';

interface ServiceAppProps {}

const MyApp = ({ Component, pageProps, router }: AppProps<ServiceAppProps>) => {
  return (
    <>
      <Head>
        <title>So You</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Global styles={globalStyles}></Global>
      <RecoilRoot>
        <AnimatePresence mode="wait">
          <Component {...pageProps} key={router.route} />
        </AnimatePresence>
      </RecoilRoot>
    </>
  );
};

export default MyApp;
