import { InfluencerDataType } from '@/types/influencer';

export const InfluencerListData: Array<InfluencerDataType> = [
  {
    influencer_id: 1,
    ranking: 1,
    working_time: 3,
    name: '유투버 이름',
    followersCount: 100,
    category: ['일상/Vlog', '뷰티'],
    youtube_link: 'https://www.youtube.com/',
    cost: 500000,
  },
  {
    influencer_id: 2,
    ranking: 2,
    working_time: 3,
    name: '유투버 이름',
    followersCount: 2000,
    category: ['펫/애완동물', '음악'],
    youtube_link: 'https://www.youtube.com/',
    cost: 1500000,
  },
  {
    influencer_id: 3,
    ranking: 3,
    working_time: 3,
    name: '유투버 이름',
    followersCount: 150,
    category: ['운세/타로'],
    youtube_link: 'https://www.youtube.com/',
    cost: 500000,
  },
  {
    influencer_id: 4,
    ranking: 4,
    working_time: 3,
    name: '유투버 이름',
    followersCount: 340,
    category: ['외국어/언어'],
    youtube_link: 'https://www.youtube.com/',
    cost: 800000,
  },
  {
    influencer_id: 5,
    ranking: 5,
    working_time: 3,
    name: '유투버 이름',
    followersCount: 62,
    category: ['게임', '커플', '트랜드'],
    youtube_link: 'https://www.youtube.com/',
    cost: 500000,
  },
];
